### PR TITLE
New solution branch2

### PR DESCRIPTION
**Pull request by Sahilkumar19**
@HarryDulaney , please take a look at this, previous (iterative ) solution was correct . I have the solution completely have solved the linear recurrence relation of fibonacci numbers and got the exact solution to find the nth fibonacci number . on further solving and observing about the time complexity it becomes O(1.6180)^n which is golden number raised to power n.

### CODE REVIEW

**Comment by HarryDulaney** [comment]
@Sahilkumar19 Hey I see you deleted Exercise07_05. If I merge this it will delete the Exercise 07_05 file on the master branch. 
image
Instead, can you please: 
1. Checkout your solution branch locally/ in you ide.
2. use the git reset command to reset your branch to your first commit 
	- updated program for Exercise01_04
3. Push again to origin/your solution branch


This should reset the commit history to the point where the only changes made were to the Exercise01_04

**Comment by HarryDulaney** [comment]
@Sahilkumar19 , actually nevermind, I found a PR you created that has only the changes to Exercise 01_04 in it. I am going to close this current one here, and I will approve the other one.

**Comment by HarryDulaney** [comment]
@Sahilkumar19 , actually nevermind, I found a PR you created that has only the changes to Exercise 01_04 in it. I am going to close this current one here, and I will approve the other one.

**Comment by Sahilkumar19** [comment]
> @Sahilkumar19 , actually nevermind, I found a PR you created that has only the changes to Exercise 01_04 in it. I am going to close this current one here, and I will approve the other one.

thanks, Now I have got the point

**Pull request closed without merging**
